/**
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pablokarin.progav.jframe;

import java.awt.Color;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import com.pablokarin.progav.part1.*;
import com.pablokarin.progav.part1.hilos.*;
import java.util.ArrayList;
import javax.swing.JScrollPane;

/**
 *
 * @author Karín
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public VentanaPrincipal() {
        initComponents();
        ExecutorService pool = Executors.newFixedThreadPool(10); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        generarAmenaza = new javax.swing.JButton();
        pausaReanudar = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        campoBuscandoComida = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoComiendo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoDescansando = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        campoInstruyendose = new javax.swing.JTextField();
        campoComidaAlmacen = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        campoComidaComedor = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        campoDefendiendo = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        campoRefugio = new javax.swing.JTextArea();
        campoEnAlmacen = new javax.swing.JTextField();
        campoLlevandoComida = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        campoDejandoComida = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        campoNHormigas = new javax.swing.JTextField();

        jScrollPane5.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hormiguero");
        setIconImage(new javax.swing.ImageIcon("Other sources/images/ormigabien.png").getImage());

        generarAmenaza.setBackground(new java.awt.Color(255, 0, 0));
        generarAmenaza.setForeground(new java.awt.Color(255, 255, 255));
        generarAmenaza.setText("Generar amenaza");
        generarAmenaza.setFocusable(false);
        generarAmenaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarAmenazaActionPerformed(evt);
            }
        });

        pausaReanudar.setText("Pausar");
        pausaReanudar.setFocusable(false);
        pausaReanudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausaReanudarActionPerformed(evt);
            }
        });

        jLabel1.setText("Hormigas buscando comida");

        campoBuscandoComida.setEditable(false);
        campoBuscandoComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBuscandoComidaActionPerformed(evt);
            }
        });

        jLabel2.setText("Hormigas comiendo");

        jLabel3.setText("Hormigas descansando");

        jLabel4.setText("Hormigas en el almacén");

        jLabel5.setText("Comida en almacén:");

        jLabel6.setText("Hormigas en el refugio");

        campoComiendo.setLineWrap(true); // Habilitar el ajuste de línea
        campoComiendo.setWrapStyleWord(true); // Ajustar palabras completas
        campoComiendo.setEditable(false);
        campoComiendo.setColumns(20);
        campoComiendo.setRows(5);
        jScrollPane1.setViewportView(campoComiendo);

        campoDescansando.setEditable(false);
        campoDescansando.setLineWrap(true); // Habilitar el ajuste de línea
        campoDescansando.setWrapStyleWord(true); // Ajustar palabras completas
        campoDescansando.setColumns(20);
        campoDescansando.setRows(5);
        jScrollPane2.setViewportView(campoDescansando);

        jLabel7.setText("Hormigas defendiendo la colonia");

        campoInstruyendose.setEditable(false);

        campoComidaAlmacen.setEditable(false);
        campoComidaAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoComidaAlmacenActionPerformed(evt);
            }
        });

        jLabel8.setText("Hormigas llevando comida");

        jLabel9.setText("Hormigas instruyendose");

        jLabel10.setText("Comida en comedor:");

        campoComidaComedor.setEditable(false);
        campoComidaComedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoComidaComedorActionPerformed(evt);
            }
        });

        campoDefendiendo.setEditable(false);
        campoDefendiendo.setColumns(20);
        campoDefendiendo.setRows(5);
        jScrollPane3.setViewportView(campoDefendiendo);

        campoRefugio.setEditable(false);
        campoRefugio.setColumns(20);
        campoRefugio.setRows(5);
        jScrollPane4.setViewportView(campoRefugio);

        campoEnAlmacen.setEditable(false);

        campoLlevandoComida.setEditable(false);
        campoLlevandoComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLlevandoComidaActionPerformed(evt);
            }
        });

        jLabel11.setText("Hormigas dejando comida");

        campoDejandoComida.setEditable(false);

        jLabel12.setText("Hormigas vivas:");

        campoNHormigas.setEditable(false);
        campoNHormigas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNHormigasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pausaReanudar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jScrollPane3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane4)
                                .addComponent(jLabel6))
                            .addComponent(generarAmenaza)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoComidaComedor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoComidaAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNHormigas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 157, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoDejandoComida, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoLlevandoComida, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoEnAlmacen)
                            .addComponent(campoInstruyendose, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoBuscandoComida))))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(campoComidaComedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(campoComidaAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(campoNHormigas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoBuscandoComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoEnAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campoLlevandoComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(campoDejandoComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(campoInstruyendose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generarAmenaza)
                    .addComponent(pausaReanudar))
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pausaReanudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausaReanudarActionPerformed
        if (pausaReanudar.isSelected())
        {
            pausaReanudar.setText("Reanudar");
            pausaReanudar.setBackground(Color.white);
            
            //insertar código para pausar hilos de mierda
        }
        if (!pausaReanudar.isSelected())
        {
            pausaReanudar.setText("Pausar");
        }
    }//GEN-LAST:event_pausaReanudarActionPerformed

    private void generarAmenazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarAmenazaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generarAmenazaActionPerformed

    private void campoComidaComedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoComidaComedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoComidaComedorActionPerformed

    private void campoBuscandoComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBuscandoComidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscandoComidaActionPerformed

    private void campoComidaAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoComidaAlmacenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoComidaAlmacenActionPerformed

    private void campoLlevandoComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLlevandoComidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLlevandoComidaActionPerformed

    private void campoNHormigasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNHormigasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNHormigasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    
    public void updateData()
    {
        campoComidaAlmacen.setText(String.valueOf(Almacen.getStock()));
        campoComidaComedor.setText(String.valueOf(Comedor.getStock()));
        campoNHormigas.setText(String.valueOf(Hormiguero.getNHormigasVivas()));
        
        String almacen = "";
        ArrayList<Obrera> lAlmacen = Hormiguero.getAlmacen();
        
         for (int i = 0; i < lAlmacen.size(); i++)
         {
            try
            {
                almacen += lAlmacen.get(i).getNombre() + ", ";
            }
            catch(Exception e){}
         }
        campoEnAlmacen.setText(almacen);
        
        String comiendo = "";
        ArrayList<Hormiga> lComer = Hormiguero.getComer();
        
        for (int i = 0; i < lComer.size(); i++)
        {
            try
            {
                comiendo += lComer.get(i).getNombre() + ", ";
            }
            catch(Exception e){}
        }
        campoComiendo.setText(comiendo);
        
        String descansando = "";
        ArrayList<Hormiga> lDescanso = Hormiguero.getDescanso();
        
        for (int i = 0; i < lDescanso.size(); i++)
        {
            try
            {
                descansando += lDescanso.get(i).getNombre() + ", ";
            }
            catch(Exception e){}
        }
        campoDescansando.setText(descansando);
        
        String fuera = "";
        ArrayList<Obrera> lFuera = Hormiguero.getFuera();
        
        for (int i = 0; i < lFuera.size();i++)
        {
            try
            {
                fuera += lFuera.get(i).getNombre() + ", ";
            }
            catch(Exception e){}
        }
        campoBuscandoComida.setText(fuera);
        
        String movimiento = "";
        ArrayList<Obrera> lMovimiento = Hormiguero.getMovimiento();
        
        for (int i = 0; i < lMovimiento.size(); i++)
        {
            try
            {
                movimiento += lMovimiento.get(i).getNombre() + ", ";
            }
            catch(Exception e){}
        }
        campoLlevandoComida.setText(movimiento);
        
        String dejandoComida = "";
        ArrayList<Obrera> lDejandoComida = Hormiguero.getDejandoComida();
        
        for (int i = 0; i < lDejandoComida.size(); i++)
        {
            try
            {
                dejandoComida += lDejandoComida.get(i).getNombre() + ", ";
            }
            catch(Exception e){}
        }
        campoDejandoComida.setText(dejandoComida);
        
        String defendiendo = "";
        ArrayList<Soldado> lDefendiendo = Hormiguero.getDefendiendo();
        
        for (int i = 0; i < lDefendiendo.size(); i++)
        {
            try
            {
                defendiendo += lDefendiendo.get(i).getNombre() + ", ";
            }
            catch(Exception e){}
        }
        campoDefendiendo.setText(defendiendo);
        
        String instruc = "";
        ArrayList<Soldado> lInstruc = Hormiguero.getInstruc();
        
        for (int i = 0; i < lInstruc.size(); i++)
        {
            try
            {
                instruc += lInstruc.get(i).getNombre() + ", ";
            }
            catch(Exception e){}
        }
        campoInstruyendose.setText(instruc);
        
        String refugio = "";
        ArrayList<Cria> lRefugio = Hormiguero.getRefugio();
        
        for (int i = 0; i < lRefugio.size(); i++)
        {
            try
            {
                refugio += lRefugio.get(i).getNombre() + ", ";
            }
            catch(Exception e){}
        }
        campoRefugio.setText(refugio);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoBuscandoComida;
    private javax.swing.JTextField campoComidaAlmacen;
    private javax.swing.JTextField campoComidaComedor;
    private javax.swing.JTextArea campoComiendo;
    private javax.swing.JTextArea campoDefendiendo;
    private javax.swing.JTextField campoDejandoComida;
    private javax.swing.JTextArea campoDescansando;
    private javax.swing.JTextField campoEnAlmacen;
    private javax.swing.JTextField campoInstruyendose;
    private javax.swing.JTextField campoLlevandoComida;
    private javax.swing.JTextField campoNHormigas;
    private javax.swing.JTextArea campoRefugio;
    private javax.swing.JButton generarAmenaza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTree jTree1;
    private javax.swing.JToggleButton pausaReanudar;
    // End of variables declaration//GEN-END:variables
}
